// Generated by oerem — do not edit manually
// Source: ../../../server/models/post.model.ts

import type { OeremQueryBuilder } from '@lalase/oerem'

import type { TUser } from './user.types.js'

export type TPost = {
  id: number
  title: string
  body: string
  user_id: number
} & RPost

export type RPost = {
  author?: TUser | null
}

export type QPost = OeremQueryBuilder<TPost, RPost>
