// Generated by oerem — do not edit manually
// Source: ../../../server/models/role.model.ts

import type { OeremQueryBuilder } from '@lalase/oerem'

import type { TUser } from './user.types.js'
import type { TUserRole } from './userrole.types.js'

export type TRole = {
  id: number
  name: string
} & RRole

export type RRole = {
  users?: (TUser & { pivot: TUserRole })[]
}

export type QRole = OeremQueryBuilder<TRole, RRole>
