// Generated by oerem — do not edit manually
// Source: ../../../server/models/user.model.ts

import type { OeremQueryBuilder } from '@lalase/oerem'

import type { TPost } from './post.types.js'
import type { TRole } from './role.types.js'
import type { TUserRole } from './userrole.types.js'

export type TUser = {
  id: number
  name: string
  email: string
  password: string
} & RUser

export type RUser = {
  posts?: TPost[]
  roles?: (TRole & { pivot: TUserRole })[]
}

export type QUser = OeremQueryBuilder<TUser, RUser>
