// Generated by oerem — do not edit manually
// Source: ../../../server/models/user.model.ts

import type { TPost } from './post.types.js'

export type TUser = {
  id: number
  name: string
  email: string
  password: string
} & RUser

export type RUser = {
  posts?: TPost[]
}
