// Generated by oerem — do not edit manually
// Source: ../../../server/models/user-role.model.ts

import type { OeremQueryBuilder } from '@lalase/oerem'

export type TUserRole = {
  id: number
  user_id: number
  role_id: number
}

export type RUserRole = Record<string, never>

export type QUserRole = OeremQueryBuilder<TUserRole, RUserRole>
