import { writeFileSync } from 'node:fs'
import { resolve, relative, dirname } from 'node:path'
import type { DiscoveredModel } from '../scanner.js'

// ─── Registry Generator ───────────────────────────────────────────────────────

export function generateRegistry(
    models: DiscoveredModel[],
    inputFolder: string,
    outputFolder: string,
    poolFile: string,
): void {
    if (models.length === 0) {
        console.warn('  ⚠ No models found. Registry not generated.')
        return
    }

    const outputIndexPath = resolve(inputFolder, 'index.ts')

    // ── Relative path from inputFolder to poolFile ────────────────────────────
    const poolRelPath = toRelativeImport(inputFolder, poolFile)

    // ── Relative path from inputFolder to outputFolder (types) ───────────────
    const typesRelPath = toRelativeImport(inputFolder, resolve(outputFolder, 'index.js'))

    const lines: string[] = [
        `// Generated by oerem — do not edit manually`,
        ``,
        `import pool from '${poolRelPath}'`,
        `import type { ${models.map(m => `T${m.def.identifier}, R${m.def.identifier}`).join(', ')} } from '${typesRelPath}'`,
        ``,
    ]

    // ── Model imports ─────────────────────────────────────────────────────────
    for (const model of models) {
        const modelRelPath = `./${model.modelName}.js`
        lines.push(`import ${lcFirst(model.def.identifier)}Model from '${modelRelPath}'`)
    }

    lines.push(``)

    // ── Model exports via pool.createModel ───────────────────────────────────
    for (const model of models) {
        const id = model.def.identifier
        lines.push(
            `export const ${id} = pool.createModel<T${id}, R${id}>(${lcFirst(id)}Model)`
        )
    }

    lines.push(``)

    writeFileSync(outputIndexPath, lines.join('\n'), 'utf-8')
    console.log(`  ✔ Generated ${outputIndexPath}`)
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toRelativeImport(fromDir: string, toFile: string): string {
    const rel = relative(fromDir, toFile)
    // Ensure it starts with ./
    const normalized = rel.startsWith('.') ? rel : `./${rel}`
    // Strip .ts extension (use .js for ESM imports)
    return normalized.replace(/\.ts$/, '.js')
}

function lcFirst(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1)
}