import { mkdirSync, writeFileSync, existsSync, readFileSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'

// ─── Generate seeder template ──────────────────────────────────────────────────

export function generateSeeder(
    seedersFolder: string,
    name: string,
): string {
    if (!existsSync(seedersFolder)) {
        mkdirSync(seedersFolder, { recursive: true })
    }

    const fileName = `${name}.seeder.ts`
    const filePath = resolve(seedersFolder, fileName)
    const content = generateSeederContent(name)

    writeFileSync(filePath, content, 'utf-8')
    console.log(`  ✔ Generated seeder: ${fileName}`)

    return filePath
}

// ─── Generate seeder template content ───────────────────────────────────────────────

function generateSeederContent(name: string): string {
    return `// Generated by oerem
import type { Knex } from 'knex'

export const seed = async function(knex: Knex): Promise<void> {
    // const seedData: any[] = []

    // for (const row of seedData) {
    //     await knex('${name}').insert(row).onConflict('id').merge()
    // }
}
`
}

// ─── Run seeder files ────────────────────────────────────────────────────────────

export async function runSeeders(
    poolFile: string,
    seedersFolder: string,
): Promise<void> {
    const { default: Knex } = await import('knex')
    const knexConfig = await loadKnexConfigFromPool(poolFile)
    const knex = Knex(knexConfig)

    try {
        if (!existsSync(seedersFolder)) {
            console.log('  Seeders folder not found, skipping.')
            return
        }

        const files = readdirSync(seedersFolder)
            .filter(f => f.endsWith('.seeder.ts'))
            .sort()

        if (files.length === 0) {
            console.log('  No seeder files found.')
            return
        }

        for (const file of files) {
            const filePath = resolve(seedersFolder, file)
            console.log(`  Running seeder: ${file}`)

            const module = await import(filePath)
            const seedFn = module.seed

            if (typeof seedFn === 'function') {
                await seedFn(knex)
                console.log(`    ✔ ${file}`)
            }
        }

        console.log('  ✔ Seeders completed.')
    } finally {
        await knex.destroy()
    }
}

// ─── Load knex config from pool file ─────────────────────────────────────────────

async function loadKnexConfigFromPool(
    poolFile: string,
): Promise<import('knex').Knex.Config> {
    const { execSync } = await import('node:child_process')
    const { createRequire } = await import('node:module')
    const { existsSync } = await import('node:fs')

    const resolved = existsSync(poolFile)
        ? poolFile
        : existsSync(`${poolFile}.ts`)
            ? `${poolFile}.ts`
            : poolFile

    const _require = createRequire(import.meta.url)
    let tsxBin: string
    try {
        const tsxPkg = _require.resolve('tsx/package.json')
        const tsxRoot = tsxPkg.replace('/package.json', '')
        const bin = `${tsxRoot}/../.bin/tsx`
        tsxBin = existsSync(bin) ? bin : 'tsx'
    } catch {
        tsxBin = 'tsx'
    }

    const script = `
import pool from ${JSON.stringify(resolved)};
const knex = pool.getKnex();
const config = knex.client.config;
process.stdout.write(JSON.stringify({
  client: config.client,
  connection: config.connection,
  pool: config.pool,
  searchPath: config.searchPath,
}));
`

    const output = execSync(`${tsxBin} --input-type=module`, {
        input: script,
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
    })

    return JSON.parse(output) as import('knex').Knex.Config
}
