import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import type { FieldMeta, ModelDef, RelationMeta, SqlColumnType } from '../../schema/types.js'
import type { DiscoveredModel } from '../scanner.js'

// ─── SQL Type → TypeScript Type ───────────────────────────────────────────────

function sqlTypeToTs(meta: FieldMeta): string {
    const base = sqlBaseType(meta.type, meta)
    return meta.isNullable ? `${base} | null` : base
}

function sqlBaseType(type: SqlColumnType, meta: FieldMeta): string {
    switch (type) {
        case 'varchar':
        case 'text':
        case 'uuid':
            return 'string'

        case 'int':
        case 'bigint':
        case 'decimal':
        case 'float':
            return 'number'

        case 'boolean':
            return 'boolean'

        case 'date':
        case 'dateTime':
        case 'timestamp':
            return 'Date'

        case 'json':
        case 'jsonb':
            return 'unknown'

        case 'enum':
            if (meta.enumValues && meta.enumValues.length > 0) {
                return meta.enumValues.map(v => `'${v}'`).join(' | ')
            }
            return 'string'

        default:
            return 'unknown'
    }
}

// ─── Relation Type → TypeScript Type ─────────────────────────────────────────

function relationToTs(rel: RelationMeta, allModels: DiscoveredModel[]): string {
    const relatedDef = rel.ref()
    const relatedIdentifier = relatedDef.identifier

    // Find the related model to get its T type name
    const found = allModels.find(m => m.def.identifier === relatedIdentifier)
    const relatedTypeName = found ? `T${found.def.identifier}` : `T${relatedIdentifier}`

    // Handle belongsToMany with pivot intersection type
    if (rel.type === 'belongsToMany' && rel.pivotRef) {
        const pivotDef = rel.pivotRef()
        const pivotIdentifier = pivotDef.identifier
        const pivotFound = allModels.find(m => m.def.identifier === pivotIdentifier)
        const pivotTypeName = pivotFound ? `T${pivotFound.def.identifier}` : `T${pivotIdentifier}`

        // For belongsToMany with pivot, wrap intersection in parentheses before adding array wrapper
        const intersectionType = `(${relatedTypeName} & { pivot: ${pivotTypeName} })`
        return `${intersectionType}[]`
    }

    return relationWrapper(rel.type, relatedTypeName)
}

function relationWrapper(type: RelationMeta['type'], typeName: string): string {
    switch (type) {
        case 'hasMany':
        case 'belongsToMany':
            return `${typeName}[]`
        case 'hasOne':
        case 'belongsTo':
            return `${typeName} | null`
    }
}

// ─── Generate Single Type File ────────────────────────────────────────────────

export function generateTypeFile(
    model: DiscoveredModel,
    allModels: DiscoveredModel[],
    outputFolder: string,
): string {
    const { def } = model
    const id = def.identifier

    const schemaFields = Object.entries(def.schema)
    const relationEntries = Object.entries(def.relations ?? {})

    // ── Collect imports for related types ──────────────────────────────────────
    const imports: string[] = []

    if (relationEntries.length > 0) {
        const relatedIdentifiers = new Set<string>()

        for (const [, rel] of relationEntries) {
            const relatedId = rel.ref().identifier
            if (relatedId !== id) {
                relatedIdentifiers.add(relatedId)
            }

            // Also collect pivot types for belongsToMany relations
            if (rel.type === 'belongsToMany' && rel.pivotRef) {
                const pivotId = rel.pivotRef().identifier
                if (pivotId !== id) {
                    relatedIdentifiers.add(pivotId)
                }
            }
        }

        for (const relId of relatedIdentifiers) {
            const relModel = allModels.find(m => m.def.identifier === relId)
            if (relModel) {
                const relOutputFile = `${relModel.def.identifier.toLowerCase()}.types`
                imports.push(`import type { T${relId} } from './${relOutputFile}.js'`)
            }
        }
    }

    // ── T{Identifier} (schema type) ───────────────────────────────────────────
    const schemaLines = schemaFields.map(([key, meta]) => {
        const tsType = sqlTypeToTs(meta)
        return `  ${key}: ${tsType}`
    })

    // ── R{Identifier} (relations type) ────────────────────────────────────────
    const relationLines = relationEntries.map(([key, rel]) => {
        const tsType = relationToTs(rel, allModels)
        return `  ${key}?: ${tsType}`
    })

    // ── Assemble file ─────────────────────────────────────────────────────────
    const lines: string[] = [
        `// Generated by oerem — do not edit manually`,
        `// Source: ${relative(outputFolder, model.filePath)}`,
        ``,
        `import type { OeremQueryBuilder } from '@lalase/oerem'`,
        ``,
    ]

    if (imports.length > 0) {
        lines.push(...imports, ``)
    }

    // Schema type
    lines.push(`export type T${id} = {`)
    lines.push(...schemaLines)

    if (relationLines.length > 0) {
        lines.push(`} & R${id}`)
    } else {
        lines.push(`}`)
    }

    lines.push(``)

    // Relation type
    if (relationLines.length > 0) {
        lines.push(`export type R${id} = {`)
        lines.push(...relationLines)
        lines.push(`}`)
        lines.push(``)
    } else {
        lines.push(`export type R${id} = Record<string, never>`)
        lines.push(``)
    }

    // Query builder type
    lines.push(`export type Q${id} = OeremQueryBuilder<T${id}, R${id}>`)
    lines.push(``)

    return lines.join('\n')
}

// ─── Generate All Type Files ──────────────────────────────────────────────────

export function generateTypes(
    models: DiscoveredModel[],
    outputFolder: string,
): void {
    if (!existsSync(outputFolder)) {
        mkdirSync(outputFolder, { recursive: true })
    }

    for (const model of models) {
        const content = generateTypeFile(model, models, outputFolder)
        const outputPath = resolve(outputFolder, `${model.def.identifier.toLowerCase()}.types.ts`)
        writeFileSync(outputPath, content, 'utf-8')
        console.log(`  ✔ Generated ${outputPath}`)
    }

    // ── Barrel export ─────────────────────────────────────────────────────────
    const barrelLines = [
        `// Generated by oerem — do not edit manually`,
        ``,
        ...models.map(m => {
            const name = m.def.identifier.toLowerCase()
            return `export type { T${m.def.identifier}, R${m.def.identifier}, Q${m.def.identifier} } from './${name}.types.js'`
        }),
        ``,
    ]

    const barrelPath = resolve(outputFolder, 'index.ts')
    writeFileSync(barrelPath, barrelLines.join('\n'), 'utf-8')
    console.log(`  ✔ Generated ${barrelPath}`)
}