import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdirSync, rmSync, existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { generateRegistry } from '../../src/cli/generators/registry.generator.js'
import { generateMigration } from '../../src/cli/generators/migration.generator.js'
import { field } from '../../src/schema/field.js'
import { hasMany } from '../../src/schema/relations.js'
import type { DiscoveredModel } from '../../src/cli/scanner.js'

// ─── Fixtures ─────────────────────────────────────────────────────────────────

function makeTmpDir(): string {
    const dir = resolve(tmpdir(), `oerem-test-${Date.now()}-${Math.random().toString(36).slice(2)}`)
    mkdirSync(dir, { recursive: true })
    return dir
}

const userModel: DiscoveredModel = {
    filePath: '/project/models/user.model.ts',
    fileName: 'user.model.ts',
    modelName: 'user.model',
    def: {
        identifier: 'User',
        table: 'users',
        schema: {
            id: field.integer().primary().build(),
            name: field.varchar(100).build(),
            email: field.varchar(255).nullable().unique().build(),
            is_active: field.boolean().default(true).build(),
        },
        relations: {
            posts: hasMany(() => postModel.def, 'user_id'),
        },
    },
}

const postModel: DiscoveredModel = {
    filePath: '/project/models/post.model.ts',
    fileName: 'post.model.ts',
    modelName: 'post.model',
    def: {
        identifier: 'Post',
        table: 'posts',
        schema: {
            id: field.integer().primary().build(),
            title: field.varchar(255).build(),
            user_id: field.integer().foreign().constrained('users').cascadeOn('delete', 'update').build(),
        },
    },
}

// ─── Registry Generator Tests ─────────────────────────────────────────────────

describe('generateRegistry', () => {
    let tmpDir: string

    beforeEach(() => { tmpDir = makeTmpDir() })
    afterEach(() => { if (existsSync(tmpDir)) rmSync(tmpDir, { recursive: true }) })

    it('generates index.ts in inputFolder', () => {
        generateRegistry([userModel, postModel], tmpDir, resolve(tmpDir, 'types'), resolve(tmpDir, 'pool.ts'))
        expect(existsSync(resolve(tmpDir, 'index.ts'))).toBe(true)
    })

    it('imports pool from poolFile', () => {
        generateRegistry([userModel], tmpDir, resolve(tmpDir, 'types'), resolve(tmpDir, 'pool.ts'))
        const content = readFileSync(resolve(tmpDir, 'index.ts'), 'utf-8')
        expect(content).toContain("import pool from './pool.js'")
    })

    it('imports model definitions', () => {
        generateRegistry([userModel, postModel], tmpDir, resolve(tmpDir, 'types'), resolve(tmpDir, 'pool.ts'))
        const content = readFileSync(resolve(tmpDir, 'index.ts'), 'utf-8')
        expect(content).toContain("import userModel from './user.model.js'")
        expect(content).toContain("import postModel from './post.model.js'")
    })

    it('exports models via pool.createModel with correct generics', () => {
        generateRegistry([userModel, postModel], tmpDir, resolve(tmpDir, 'types'), resolve(tmpDir, 'pool.ts'))
        const content = readFileSync(resolve(tmpDir, 'index.ts'), 'utf-8')
        expect(content).toContain('export const User = pool.createModel<TUser, RUser>(userModel)')
        expect(content).toContain('export const Post = pool.createModel<TPost, RPost>(postModel)')
    })

    it('imports types from outputFolder', () => {
        generateRegistry([userModel], tmpDir, resolve(tmpDir, 'types'), resolve(tmpDir, 'pool.ts'))
        const content = readFileSync(resolve(tmpDir, 'index.ts'), 'utf-8')
        expect(content).toContain("from './types/index.js'")
    })

    it('warns and skips if no models', () => {
        generateRegistry([], tmpDir, resolve(tmpDir, 'types'), resolve(tmpDir, 'pool.ts'))
        expect(existsSync(resolve(tmpDir, 'index.ts'))).toBe(false)
    })

    it('adds generated-by comment', () => {
        generateRegistry([userModel], tmpDir, resolve(tmpDir, 'types'), resolve(tmpDir, 'pool.ts'))
        const content = readFileSync(resolve(tmpDir, 'index.ts'), 'utf-8')
        expect(content).toContain('Generated by oerem')
    })
})

// ─── Migration Generator Tests ────────────────────────────────────────────────

describe('generateMigration', () => {
    let tmpDir: string
    let migrationsDir: string

    beforeEach(() => {
        tmpDir = makeTmpDir()
        migrationsDir = resolve(tmpDir, 'migrations')
        mkdirSync(migrationsDir, { recursive: true })
    })
    afterEach(() => { if (existsSync(tmpDir)) rmSync(tmpDir, { recursive: true }) })

    it('throws if migrations folder does not exist', () => {
        const missing = resolve(tmpDir, 'nonexistent')
        expect(() => generateMigration([userModel], missing)).toThrow('Migrations folder not found')
    })

    it('generates a migration file', () => {
        const filePath = generateMigration([userModel], migrationsDir)
        expect(existsSync(filePath)).toBe(true)
        expect(filePath).toMatch(/\.ts$/)
    })

    it('migration file has up and down exports', () => {
        const filePath = generateMigration([userModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain('export async function up')
        expect(content).toContain('export async function down')
    })

    it('migration creates correct table', () => {
        const filePath = generateMigration([userModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain("createTable('users'")
    })

    it('migration generates increments for integer primary', () => {
        const filePath = generateMigration([userModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain("increments('id')")
    })

    it('migration generates varchar with length', () => {
        const filePath = generateMigration([userModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain("string('name', 100)")
    })

    it('migration generates nullable column', () => {
        const filePath = generateMigration([userModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain("string('email', 255).nullable().unique()")
    })

    it('migration generates boolean with default', () => {
        const filePath = generateMigration([userModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain("boolean('is_active').notNullable().defaultTo(true)")
    })

    it('migration generates foreign key with cascade', () => {
        const filePath = generateMigration([postModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain("foreign('user_id').references('id').inTable('users')")
        expect(content).toContain(".onDelete('CASCADE')")
        expect(content).toContain(".onUpdate('CASCADE')")
    })

    it('migration drops tables in reverse order in down()', () => {
        const filePath = generateMigration([userModel, postModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        const downIdx = content.indexOf('async function down')
        const dropUsers = content.indexOf("dropTableIfExists('users')", downIdx)
        const dropPosts = content.indexOf("dropTableIfExists('posts')", downIdx)
        expect(dropPosts).toBeLessThan(dropUsers)
    })

    it('uses custom migration name', () => {
        const filePath = generateMigration([userModel], migrationsDir, 'add_users_table')
        expect(filePath).toContain('add_users_table')
    })

    it('uuid primary key uses uuid() not increments()', () => {
        const uuidModel: DiscoveredModel = {
            filePath: '/project/models/token.model.ts',
            fileName: 'token.model.ts',
            modelName: 'token.model',
            def: {
                identifier: 'Token',
                table: 'tokens',
                schema: {
                    id: field.uuid().primary().build(),
                    value: field.text().build(),
                },
            },
        }

        const filePath = generateMigration([uuidModel], migrationsDir)
        const content = readFileSync(filePath, 'utf-8')
        expect(content).toContain("uuid('id')")
        expect(content).not.toContain("increments('id')")
    })
})