// Generated by oerem — do not edit manually

import pool from '../core/pool.js'
import type { TPost, RPost, TUser, RUser } from '../../shared/types/models/index.js'

import postModel from './post.model.js'
import userModel from './user.model.js'

export const Post = pool.createModel<TPost, RPost>(postModel)
export const User = pool.createModel<TUser, RUser>(userModel)
