// Generated by oerem — do not edit manually

import pool from '../core/pool.js'
import type { TPost, RPost, TRole, RRole, TUserRole, RUserRole, TUser, RUser } from '../../shared/types/models/index.js'

import postModel from './post.model.js'
import roleModel from './role.model.js'
import userRoleModel from './user-role.model.js'
import userModel from './user.model.js'

export const Post = pool.createModel<TPost, RPost>(postModel)
export const Role = pool.createModel<TRole, RRole>(roleModel)
export const UserRole = pool.createModel<TUserRole, RUserRole>(userRoleModel)
export const User = pool.createModel<TUser, RUser>(userModel)
