// Generated by oerem
import type { Knex } from 'knex'

export const seed = async function (knex: Knex): Promise<void> {
    // const seedData: any[] = []

    // for (const row of seedData) {
    //     await knex('database').insert(row).onConflict('id').merge()
    // }
    await knex('users').insert({
        email: 'user1@example.com',
        name: 'User1',
        password: '$2a$10$abcdefghijklmnopqrstuvwxy.zABCDEFGHIJKLMNOPQRSTUVWXY'
    })
}
